-d C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\debouncer\impl\gwsynthesis\debouncer.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\debouncer\src\deb.cst
-cfg C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\debouncer\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
