-d C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\adc_card\impl\gwsynthesis\ADC_receiver.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\adc_card\src\pinos.cst
-cfg C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\adc_card\impl\pnr\device.cfg
-gao_crc 0100101000111011
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
-rtl_gao
