-d D:\GowinProjects\adc_card\impl\gwsynthesis\adc_card.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst D:\GowinProjects\adc_card\src\pinos.cst
-cfg D:\GowinProjects\adc_card\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
