-d C:\Pessoal\TCC\GowinProjects\Tang_Nano_1k\impl\gwsynthesis\Tang_Nano_1k.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cfg C:\Pessoal\TCC\GowinProjects\Tang_Nano_1k\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
