-d C:\Tupao\GowinFPGA\GowinProjects\Tang_Nano_1k\impl\gwsynthesis\Tang_Nano_1k.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Tupao\GowinFPGA\GowinProjects\Tang_Nano_1k\src\Tang_Nano_1k.cst
-cfg C:\Tupao\GowinFPGA\GowinProjects\Tang_Nano_1k\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 10
