-d C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Neo_Data_acquisition_ADC\impl\gwsynthesis\Neo_Acquisition.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Neo_Data_acquisition_ADC\src\PSRAM_UART_pins.cst
-cfg C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Neo_Data_acquisition_ADC\impl\pnr\device.cfg
-sdc C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Neo_Data_acquisition_ADC\src\Neo_Acquisition.sdc
-bit
-tr
-ph
-tt
-timing
-replicate
-cst_error
-place_option 2
-route_option 1
-clock_route_order 1
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
