-d C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Data_acquisition_expansion\impl\gwsynthesis\Data_acquisition.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Data_acquisition_expansion\src\PSRAM_UART_pins.cst
-cfg C:\Users\GuilhermeY\Github\GowinFPGA\GowinProjects\Data_acquisition_expansion\impl\pnr\device.cfg
-bit
-tr
-ph
-tt
-timing
-cst_error
-place_option 2
-route_option 1
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
